### ISSUE TITLE
Add option to disable or enable block break

### ISSUE THREAD

**Issue by vitiacat** [jeremynoesen/VolleyBall#25]
Hello! Can you add option to enable block break in court? It will be cool option for survival servers :cat:

**Comment by jeremynoesen** [comment]
This is a great idea, and I'm surprised I didn't think of it before. I can totally add this to the next version! Due to time, I might not get to this for another few weeks.

**Comment by jeremynoesen** [comment]
Sorry to push this off way too long. This has been implemented in the 1.2.0 branch, and will be included whenever the release comes out. I can't guarantee that will be soon, seeing how long it took me to get to this.
